### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by we125182** [TwanoO67/ng2-admin-lte#48]
Hi,guys,
Afer run "npm install", when I  run npm start, a error occurs. 
```
> ng2-admin-lte@0.7.0 start D:\project\github\AngularProject\ng2-admin-lte
> ng serve

can't resolve module @angular/core/src/di/opaque_token from D:\project\github\AngularProject\ng2-admin-lte\src\index.ts
Cannot read property 'parse' of undefined
TypeError: Cannot read property 'parse' of undefined
    at ReflectorHost.normalizeAssetUrl (D:\project\github\AngularProject\ng2-admin-lte\node_modules\@angular\compiler-cli\src\reflector_host.js:54:43)
    at ReflectorHost.findDeclaration (D:\project\github\AngularProject\ng2-admin-lte\node_modules\@angular\compiler-cli\src\reflector_host.js:151:33)
    at StaticReflector.initializeConversionMap (D:\project\github\AngularProject\ng2-admin-lte\node_modules\@angular\compiler-cli\src\static_reflector.js:145:38)
    at new StaticReflector (D:\project\github\AngularProject\ng2-admin-lte\node_modules\@angular\compiler-cli\src\static_reflector.js:42:14)
    at AotPlugin._setupOptions (D:\project\github\AngularProject\ng2-admin-lte\node_modules\@ngtools\webpack\src\plugin.js:137:27)
    at new AotPlugin (D:\project\github\AngularProject\ng2-admin-lte\node_modules\@ngtools\webpack\src\plugin.js:37:14)
    at Object.exports.getWebpackNonAotConfigPartial (D:\project\github\AngularProject\ng2-admin-lte\node_modules\angular-cli\models\webpack-build-typescript.js:20:13)
    at new NgCliWebpackConfig (D:\project\github\AngularProject\ng2-admin-lte\node_modules\angular-cli\models\webpack-config.js:23:42)
    at Class.run (D:\project\github\AngularProject\ng2-admin-lte\node_modules\angular-cli\tasks\serve-webpack.js:20:22)
    at D:\project\github\AngularProject\ng2-admin-lte\node_modules\angular-cli\commands\serve.js:102:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! ng2-admin-lte@0.7.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-admin-lte@0.7.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-admin-lte package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-admin-lte
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-admin-lte
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\project\github\AngularProject\ng2-admin-lte\npm-debug.log
```
and I can't find the file in the path “D:\project\github\AngularProject\ng2-admin-lte\src\index.ts”.
how to resolve this problem? appreciate everyone for help.

**Comment by TwanoO67** [comment]
It's seems related to the angular 2.3.0 update, will keep you posted when I have solution, but for now you can revert to 2.2.X

**Comment by we125182** [comment]
@TwanoO67 thank you for your help. Follow your suggestion, start the project. But there is something wrong. open the chrome broswer, it looks like this.
![image](https://cloud.githubusercontent.com/assets/17947588/21000132/13ce3b48-bd54-11e6-979a-c41ad79214fb.png)
Like other files don't load in. Is this common?

**Comment by TwanoO67** [comment]
Yes there's a régression on the resize détection. 
But you can acces the other pages by login in the upper side right

**Comment by we125182** [comment]
I see. thank you. After I login in, I can access the other pages.

**Comment by TwanoO67** [comment]
Can you provide a PR with your package.json used to revert ?
