### ISSUE TITLE
Building with docker error

### ISSUE THREAD

**Issue by shadik42** [TwanoO67/ng2-admin-lte#72]
I run `./bin/prod.sh`

There is output of command:

```
...
npm info using npm@4.1.2
npm info using node@v7.5.0
...
ng build --prod

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/usr/src/app/node_modules/typescript/lib/typescript.js:8980:109)
    at parseSourceFileWorker (/usr/src/app/node_modules/typescript/lib/typescript.js:8940:26)
    at Object.parseSourceFile (/usr/src/app/node_modules/typescript/lib/typescript.js:8899:26)
    at Object.createSourceFile (/usr/src/app/node_modules/typescript/lib/typescript.js:8727:29)
    at VirtualFileStats.getSourceFile (/usr/src/app/node_modules/@ngtools/webpack/src/compiler_host.js:65:35)
    at WebpackCompilerHost.getSourceFile (/usr/src/app/node_modules/@ngtools/webpack/src/compiler_host.js:212:38)
    at findSourceFile (/usr/src/app/node_modules/typescript/lib/typescript.js:45859:29)
    at processImportedModules (/usr/src/app/node_modules/typescript/lib/typescript.js:45994:25)
    at findSourceFile (/usr/src/app/node_modules/typescript/lib/typescript.js:45888:17)
    at processSourceFile (/usr/src/app/node_modules/typescript/lib/typescript.js:45790:27)
    at processRootFile (/usr/src/app/node_modules/typescript/lib/typescript.js:45694:13)
    at /usr/src/app/node_modules/typescript/lib/typescript.js:45151:60
    at Object.forEach (/usr/src/app/node_modules/typescript/lib/typescript.js:1115:30)
    at Object.createProgram (/usr/src/app/node_modules/typescript/lib/typescript.js:45151:16)
    at AotPlugin._setupOptions (/usr/src/app/node_modules/@ngtools/webpack/src/plugin.js:121:28)
    at new AotPlugin (/usr/src/app/node_modules/@ngtools/webpack/src/plugin.js:22:14)
    at _createAotPlugin (/usr/src/app/node_modules/@angular/cli/models/webpack-configs/typescript.js:54:12)
    at Object.exports.getAotConfig (/usr/src/app/node_modules/@angular/cli/models/webpack-configs/typescript.js:102:13)
    at new NgCliWebpackConfig (/usr/src/app/node_modules/@angular/cli/models/webpack-config.js:23:37)
    at Class.run (/usr/src/app/node_modules/@angular/cli/tasks/build.js:24:31)
    at Class.run (/usr/src/app/node_modules/@angular/cli/commands/build.js:63:26)
    at Class.<anonymous> (/usr/src/app/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm info lifecycle ng2-admin-lte@0.8.0~prod: Failed to exec prod script
npm ERR! Linux 4.9.8-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prod"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! ng2-admin-lte@0.8.0 prod: `ng build --prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng2-admin-lte@0.8.0 prod script 'ng build --prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-admin-lte package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build --prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-admin-lte
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-admin-lte
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

```
Maybe i doing something wrong, can you help me please?

**Comment by TwanoO67** [comment]
Usually this error came when you had node_modules coming from an old angular-cli installation. 

Try removing your node_modules and loading. /bin/start.sh

**Comment by shadik42** [comment]
I removed node_modules from project and from system and run `./bin/start.sh` but nothing changed, I still have error. 

Can you check on your system, please?

**Comment by TwanoO67** [comment]
I dont have any computer at the moment but it was working yesterday when I added that...

**Comment by xai1981** [comment]
For "npm run prod" you need "./src/environments/ environment.prod.ts".

It is also possible to do as follows.

```
diff --git a/angular-cli.json b/angular-cli.json
index 42f95f6..acb418c 100644
--- a/angular-cli.json
+++ b/angular-cli.json
@@ -25,7 +25,7 @@
       "environmentSource": "environments/environment.ts",
       "environments": {
         "dev": "environments/environment.ts",
-        "prod": "environments/environment.prod.ts"
+        "prod": "environments/environment.ts"
       }
     }
   ],
```
